import { useState, useRef, useEffect } from "react";
import { Alert } from "react-native";
import { ProductService } from "../services/ProductService";
import { isValidAssetCodeFormat } from "../utils/qr";
import type { Product } from "../types/Product";

const TARGET_SIZE = 240;
const MIN_QR_SIZE = 110;
const MULTI_QR_WINDOW_MS = 400;
const RESULT_DELAY_MS = 800;

interface UseScannerParams {
  screenWidth: number;
  screenHeight: number;
  isAdmin: boolean;
  onNavigateToRegister: (scannedCode: string) => void;
  onNavigateToDetails: (product: Product) => void;
}

export function useScanner({
  screenWidth,
  screenHeight,
  isAdmin,
  onNavigateToRegister,
  onNavigateToDetails,
}: UseScannerParams) {
  const [scanned, setScanned] = useState(false);
  const [guideText, setGuideText] = useState(
    "Fit the QR code inside the frame",
  );
  const [isAligned, setIsAligned] = useState(false);
  const [isCheckingDB, setIsCheckingDB] = useState(false);

  const seenDataFrames = useRef<{ [key: string]: number }>({});
  const isMountedRef = useRef(true);

  useEffect(() => {
    return () => {
      isMountedRef.current = false;
    };
  }, []);

  const resetScannerState = () => {
    setScanned(false);
    setIsAligned(false);
    setIsCheckingDB(false);
    setGuideText("Fit the QR code inside the frame");
    seenDataFrames.current = {};
  };

  const handleBarcodeScanned = async (event: any) => {
    if (scanned) return;

    const { bounds, data } = event;
    if (!bounds) return;

    const { origin, size } = bounds;
    if (!origin || !size) return;

    const rawQrPayload = data.trim();
    const now = Date.now();

    // 1. Multi-QR detection
    seenDataFrames.current[data] = now;
    Object.keys(seenDataFrames.current).forEach((key) => {
      if (now - seenDataFrames.current[key] > MULTI_QR_WINDOW_MS) {
        delete seenDataFrames.current[key];
      }
    });
    if (Object.keys(seenDataFrames.current).length > 1) {
      setGuideText("Multiple QRs detected! Isolate only 1");
      setIsAligned(false);
      return;
    }

    // 2. Distance check
    if (size.width < MIN_QR_SIZE || size.height < MIN_QR_SIZE) {
      setGuideText("Move closer to fill the box");
      setIsAligned(false);
      return;
    }

    // 3. Bounds/alignment check
    const targetLeft = (screenWidth - TARGET_SIZE) / 2;
    const targetTop = (screenHeight - TARGET_SIZE) / 2;
    const targetRight = targetLeft + TARGET_SIZE;
    const targetBottom = targetTop + TARGET_SIZE;

    const qrLeft = origin.x;
    const qrTop = origin.y;
    const qrRight = qrLeft + size.width;
    const qrBottom = qrTop + size.height;

    const insideBox =
      qrLeft >= targetLeft - 30 &&
      qrRight <= targetRight + 30 &&
      qrTop >= targetTop - 30 &&
      qrBottom <= targetBottom + 30;

    if (!insideBox) {
      setGuideText("Center the QR code in the box");
      setIsAligned(false);
      return;
    }

    // 4. Format validation — only accept codes this app actually generated
    if (!isValidAssetCodeFormat(rawQrPayload)) {
      setIsAligned(true);
      setScanned(true);
      Alert.alert(
        "Invalid QR Code",
        "This QR code was not generated by this app and cannot be used here.",
        [{ text: "Scan Another", onPress: resetScannerState }],
      );
      return;
    }

    // 5. Locked — check Firestore
    setIsAligned(true);
    setGuideText("Target Lock! Checking Database...");
    setScanned(true);
    setIsCheckingDB(true);

    try {
      const product = await ProductService.findProductByQRCode(rawQrPayload);

      setTimeout(() => {
        if (!isMountedRef.current) return;
        setIsCheckingDB(false);

        if (product) {
          // Any role: known QR → show its details
          onNavigateToDetails(product);
          resetScannerState();
        } else {
          if (!isAdmin) {
            Alert.alert(
              "Access Restricted",
              "This QR code isn't registered yet. Only admins can add new products.",
              [{ text: "OK", onPress: resetScannerState }],
            );
            return;
          }
          onNavigateToRegister(rawQrPayload);
          resetScannerState();
        }
      }, RESULT_DELAY_MS);
    } catch (error) {
      console.error("Scanning verification failed:", error);
      if (!isMountedRef.current) return;
      setIsCheckingDB(false);
      Alert.alert("Sync Error", "Could not check cloud database.");
      resetScannerState();
    }
  };

  return {
    scanned,
    guideText,
    isAligned,
    isCheckingDB,
    handleBarcodeScanned,
    resetScannerState,
  };
}
