/**
 * The format every asset code/QR code generated by this app follows.
 * Used to validate that a scanned QR was actually produced by this
 * system, rejecting any unrelated QR code (URLs, barcodes, etc.).
 */
const ASSET_CODE_PATTERN = /^ASYA-\d{4}$/;

/**
 * Generates a single candidate asset code in the AST-#### format.
 * Callers are responsible for checking uniqueness against Firestore
 * before treating this as final (see ProductService.isAssetCodeTaken
 * and the generatedCodes collection check in AddQrCode.tsx).
 */
export function generateAssetCode(): string {
  const randomPart = Math.floor(1000 + Math.random() * 9000);
  return `ASYA-${randomPart}`;
}

/**
 * Returns true only if the given string matches this app's own
 * generated asset code format. Used by the scanner to reject QR
 * codes that weren't produced by this system.
 */
export function isValidAssetCodeFormat(code: string): boolean {
  return ASSET_CODE_PATTERN.test(code);
}
